topic:
  name: logging
  partitions-num: 3
  replication-factor: 1

server:
  port: 8000

spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    #    properties:
    #      schema.registry.url: http://localhost:8081
    consumer:
      group-id: group_id
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        specific.avro.reader: true
        schema.registry.url: http://localhost:8081
        interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        specific.avro.reader: true
        schema.registry.url: http://localhost:8081
        interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
    template:
      default-topic:

  resources:
    add-mappings: false

  datasource:
    third:
      driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
      jdbc-url: jdbc:clickhouse://localhost:8123/default
      connection-timeout: 20000
      maxium-pool-size: 5
    type: ru.yandex.clickhouse.ClickHouseDataSource
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    url: jdbc:clickhouse://localhost:8123/default
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true



logging:
  level:
    root: info